# FOSSA Configuration
# Configure license scanning and policy for ShopMatch Pro
# Documentation: https://docs.fossa.com/docs/configuration-file

version: 3

project:
  name: shopmatch-pro
  team: development
  policy: default
  link: https://github.com/RazonIn4K/shopmatch-pro

# Targets to analyze
targets:
  only:
    - type: npm
      path: .

# Custom license policy
policies:
  - id: default
    title: ShopMatch Pro License Policy
    description: Accepts permissive open-source licenses compatible with commercial use

    # Allowed license categories
    allow:
      - MIT
      - Apache-2.0
      - BSD-2-Clause
      - BSD-3-Clause
      - ISC
      - CC0-1.0
      - Unlicense
      - LGPL-3.0-or-later  # Acceptable for library usage (Sharp/libvips)
      - MPL-2.0            # Weak copyleft, acceptable for commercial use (Next.js)

    # Licenses that require review (strong copyleft)
    flag:
      - GPL-3.0
      - AGPL-3.0

    # Explicitly denied licenses (strong copyleft, incompatible)
    deny:
      - AGPL-1.0
      - SSPL-1.0  # Not OSI approved
      - Commons-Clause  # Not open source

# Package-specific overrides and ignore rules
overrides:
  # node-forge: Dual-licensed (BSD-3-Clause OR GPL-2.0)
  # We elect to use BSD-3-Clause license
  - locator: npm+node-forge@1.3.1
    license: BSD-3-Clause
    reason: |
      node-forge is dual-licensed (BSD-3-Clause OR GPL-2.0).
      We elect to use the BSD-3-Clause license option, which is fully
      compatible with commercial and proprietary software.
      GPL-2.0 and GPL-1.0-only detections are false positives from
      license history and should be ignored.
      Documentation: THIRD_PARTY_LICENSES.md

  # glob: ISC code license, CC-BY-SA-4.0 logo only
  # We don't use or distribute the logo
  - locator: npm+glob$
    license: ISC
    reason: |
      Glob package code is ISC licensed. The CC-BY-SA-4.0 license
      applies only to the glob logo artwork file, which we do not use,
      import, or distribute. We only use the ISC-licensed code.
      Documentation: THIRD_PARTY_LICENSES.md

# Ignore rules for false positives
ignore:
  # node-forge GPL false positives (we elect BSD-3-Clause from dual-license)
  - type: license
    locator: npm+node-forge@1.3.1
    licenses:
      - GPL-1.0-only
      - GPL-2.0-only
    reason: |
      node-forge offers dual-license choice (BSD-3-Clause OR GPL-2.0).
      We elect BSD-3-Clause. GPL detections are false positives from
      license history and should be ignored.

  # Next.js CC-BY-SA-4.0 false positive (glob logo artwork, not used)
  - type: license
    locator: npm+next@15.5.5
    licenses:
      - CC-BY-SA-4.0
    reason: |
      CC-BY-SA-4.0 detection is for glob logo artwork included in Next.js.
      We do not use or distribute logo artwork. All code we use is MIT/ISC licensed.

# Exclude development and test dependencies from production scans
analyze:
  exclude:
    - type: npm
      scope: dev  # devDependencies don't affect production licensing

# Comments and notes
comments:
  licensing_strategy: |
    ShopMatch Pro uses only permissively-licensed dependencies that allow
    commercial use, modification, and redistribution. All dependencies
    have been reviewed for license compatibility. LGPL and MPL licenses
    are accepted for library usage where we do not modify the source code.

  dual_license_policy: |
    When a dependency offers dual-license options (e.g., "BSD-3-Clause OR GPL-2.0"),
    we explicitly document our license choice. Our policy is to select the most
    permissive license option that is compatible with commercial use.

  copyleft_acceptable: |
    LGPL-3.0-or-later (Sharp/libvips): Acceptable under LGPL library exception.
    These are pre-compiled binaries used as-is without modification.
    MPL-2.0 (Next.js): Weak copyleft (file-level), compatible with commercial use.
    We do not modify Next.js source code.

  false_positives: |
    Some dependencies may flag licenses for non-code assets (artwork, logos, etc.)
    that are not used or distributed in the application. These are documented
    in THIRD_PARTY_LICENSES.md with explanations.

  investigation_date: |
    Last comprehensive license audit: 2025-10-17
    See docs/FOSSA_LICENSE_REVIEW_2025-10-17.md for detailed findings.

# Experimental features
experimental:
  # Enable license inference for packages without explicit license field
  enable-license-scanning: true

  # Enable SPDX identifier support
  enable-spdx: true

# Additional notes for FOSSA users
# --------------------------------
# - Automatic scanning: FOSSA uses this configuration by default when scanning the repository.
# - Policy overrides: Document any dual-license choices in the `overrides` section.
# - Documentation: Keep rationales in THIRD_PARTY_LICENSES.md.
# - Resolving conflicts:
#     * Check whether the package is dual-licensed.
#     * Record the chosen license in `.fossa.yml`.
#     * Update THIRD_PARTY_LICENSES.md with the reasoning.
#     * Re-run the scan and clear the alert in the FOSSA UI.
