stages:
  - test

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
