stages:
  - test
  - dast

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.v2.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

variables:
  DAST_WEBSITE: "https://shopmatch.highencodelearning.com"

dast:
  stage: dast
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: true
    - when: never
